- name: apply wawe
  shell:
    cmd: |
      kubectl apply -f "https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml"
  register: out

- debug:
    msg: "{{ out }}"