- name: copy {{ service_name }} service
  template:
    dest: "{{ systemd_unit_dir }}/{{ service_name }}.service"
    src: "{{ service_name }}.service"
    mode: 0644
    owner: root
  notify: restart service

- name: start {{ service_name }} service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes

