- name: dns addons
  shell:
    cmd: |
      kubectl apply -f https://raw.githubusercontent.com/mmumshad/kubernetes-the-hard-way/master/deployments/coredns.yaml
  register: out

- debug:
    msg: "{{ out }}"